config/routes.rb
Rails.application.routes.draw do

  resources :tareas, only: [:index, :show] do
    resources :user_tasks, only: [:create, :update]
  end

  resources :user_task, only: [:index]

  root to: 'tareas#index'

devise_for :users , controllers: {
  registrations: 'user/registrations'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tarea.rb
class Tarea < ApplicationRecord
  has_many :user_tasks
  has_many :users, through: :user_tasks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_tasks
  has_many :tareas, through: :user_tasks
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :tarea
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  def index
    @tareas = Tarea.all
    @todo = UserTask.where(user: current_user)
  end

  def show
    # @tareadetalle = Tarea.find_by name: :tarea_id
    @tarea = Tarea.find(params[:id]) #funciona
    @ut = UserTask.where(tarea_id: @tarea, completada: true)
    @uttop5 = UserTask.where(tarea_id: @tarea, completada: true).order('updated_at asc').limit(5)
    @usuariostarea = User.where(id: UserTask.where(tarea_id: @tarea, completada: true))


# UserTask.select(Arel.star).where(UserTask.arel_table[:tarea_id].in([1, 2, 3]))

    # @idedelatarea = params[:tarea]
    # @usertask = UserTask.where(tarea: :tarea_id)
    # @usuariostarea = User.where(id: @usertask)
    # @usrcompletada = User.where(user: @usertask.user_id)
    # @tareascompletadas = UserTask.where(user: current_user).count
    # @tareastotales = Tarea.all.count
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :imagen])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
  before_action :authenticate_user!

  def create
    @tarea = Tarea.find(params[:tarea_id])

    # @user_task = UserTask.find_or_create_by(user: current_user, tarea: @tarea)

    @user_task = UserTask.find_by(user: current_user, tarea: @tarea)

    if @user_task == nil
      @user_task = UserTask.create(user: current_user, tarea: @tarea)
    end

    if @user_task.completada == true
      @user_task.completada = false
    else
      @user_task.completada = true
    end


    if @user_task.save
      redirect_to root_path, notice: 'Tarea completada'
    else
      redirect_to root_path, alert: 'La tarea no se completó'
    end
  end

  def index
    @usertask = current_user.user_tasks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- <a class="navbar-brand" href="#">Navbar</a> -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active"><%= link_to 'Inicio', root_path, :class => 'nav-link' %></li>
      <li class="nav-item active">
        <a class="nav-link" href="#"> Completadas
          <%= UserTask.where(user: current_user).count %> / Totales
          <%= Tarea.all.count %>
           <span class="sr-only">(current)</span></a>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link" href="#">Lista de tareas</a>
      </li> -->
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
      <li class="nav-item">

        <% if user_signed_in? %>
          <li class="nav-item active">
          <%= link_to current_user.name, destroy_user_session_path, method: :delete, :class => 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item active">
          <%= link_to 'Login', new_user_session_path, :class => 'nav-link'   %>
          </li>
        <% end %>

      </li>
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp18sep</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Nombre categoría: </strong>
  <%= @category.name %>
</p>

<p>Crear producto</p>
<%= form_with(model: [@category, @product]) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>




<table class="table .table-bordered">
  <tr>
    <th>Nombre</th>
    <th>Precio</th>
  </tr>
  <% @products.each do |p| %>
    <!-- <%if p.category_id == @category.id%> -->
    <tr>
      <td><%=p.name%></td>
      <td><%=p.price%></td>
      <td><%=link_to "Borrar", category_product_path(@category, p), method: :delete, class: 'btn btn-danger'%></td>
    </tr>
    <!-- <%end%> -->
  <% end %>
</table>







<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/tareas/index.html.erb
<div class="container">
  <div class="row">
    <% @tareas.each_slice(3) do |row| %>
    <%row.each do |tarea| %>
      <div class="col">
        <div class="card">
          <%= image_tag tarea.photo, class: 'card-img-top'%>
            <div class="body">
              <h5><%= link_to tarea.name, tarea_path(tarea)%></h5>
              <% if @todo.find_by(tarea: tarea) and @todo.find_by(tarea: tarea).completada%>
                <%= link_to "Descompletar", tarea_user_tasks_path(tarea), class: 'btn btn-danger', method: :post%>
              <% else %>
                <%= link_to "Completar", tarea_user_tasks_path(tarea), class: 'btn btn-success', method: :post%>
              <% end%>
            </div>
          </div>
        </div>
      <% end %>
      <div class="w-100" style="margin-top:20px"> </div>
    <% end %>
  </div>
</div>

app/views/tareas/show.html.erb
<h2> Tarea: <%= @tarea.name %></h2>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <table class="table">
        <tr>
          <th>Top 5 </th>
        </tr>
        <% @uttop5.each do |usr| %>
        <tr>
          <td><%= User.find_by(id: usr.user_id).name %></td>
          <td><%= image_tag User.find_by(id: usr.user_id).imagen, class: 'card-img-top'%></td>
        </tr>

        <% end %>
      </table>
    </div>

    <div class="col-md-3">
      <table class="table">
        <tr>
          <th>Tarea completada por: </th>
        </tr>
        <% @ut.each do |usr| %>
        <tr>
          <td><%= User.find_by(id: usr.user_id).name %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/user_tasks/index.html.erb
<table class="table">
  <% @usertask.each do |usrt| %>
  <tr>
    <td><%= usrt.tarea.email %></td>
  </tr>
  <% end %>
</table>